// Strings that the live-site dictionary does not carry (new site elements).
export const EXTRA = {
  en: {
    trustedBy: 'Used by 10 companies across the UAE',
    proof: 'Used by 10 companies across the UAE — including LBMC, an FTA-registered tax agency',
    liveTag: 'LIVE',
    seeHow: 'See how it works',
    whatsapp: 'WhatsApp us',
    sendWhatsapp: 'Send via WhatsApp',
    sendEmail: 'Send via email',
    payZiina: 'Pay securely with Ziina',
    ziinaHandle: 'Ziina handle',
    perReturn: 'per return',
    fiveFor: 'Five returns for AED 2,750',
    getStarted: 'Open the free app',
    prefillNote: 'Your message will open in WhatsApp or your email app — nothing is stored on this site.',
    deadlineIn: (d) => `${d} days`,
    overdue: 'Overdue',
    sampleCo: 'Sample taxpayer',
    open: 'open',
    of: 'of',
    riskScore: 'Risk score',
    areasNone: 'No specific gaps flagged — keep records current.',
    readMore: 'Read more',
    included: 'Included',
    monthLabels: ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'],
    preview: 'Preview',
    lastReviewed: 'Last reviewed',
    reportSubject: 'My TaxCheck risk check result',
    demoSubject: 'Demo request',
    careerSubject: 'Job application',
    contactSubject: 'Website enquiry',
    chooseRole: 'Choose a role',
    selectOne: 'Select…',
    days: 'days',
    calEmpty: 'No deadlines in the next 90 days.',
    scrollHint: 'Scroll',
    minute: 'min',
    qa: 'Q&A',
    docsPerMin: 'documents read per minute',
  },
  ar: {
    trustedBy: 'تستخدمه 10 شركات في الإمارات',
    proof: 'تستخدمه 10 شركات في الإمارات — من بينها LBMC، وكالة ضريبية مسجّلة لدى الهيئة الاتحادية للضرائب',
    liveTag: 'مباشر',
    seeHow: 'كيف يعمل؟',
    whatsapp: 'راسلنا على واتساب',
    sendWhatsapp: 'إرسال عبر واتساب',
    sendEmail: 'إرسال عبر البريد',
    payZiina: 'ادفع بأمان عبر Ziina',
    ziinaHandle: 'معرّف Ziina',
    perReturn: 'لكل إقرار',
    fiveFor: 'خمسة إقرارات بـ 2,750 درهم',
    getStarted: 'افتح التطبيق مجاناً',
    prefillNote: 'ستُفتح رسالتك في واتساب أو تطبيق البريد لديك — لا يُخزَّن أي شيء على هذا الموقع.',
    deadlineIn: (d) => `${d} يوماً`,
    overdue: 'متأخر',
    sampleCo: 'مكلّف تجريبي',
    open: 'مفتوحة',
    of: 'من',
    riskScore: 'درجة المخاطر',
    areasNone: 'لم تُرصد فجوات محددة — حافظ على تحديث السجلات.',
    readMore: 'اقرأ المزيد',
    included: 'مشمول',
    monthLabels: ['ي', 'ف', 'م', 'أ', 'م', 'ي', 'ي', 'أ', 'س', 'أ', 'ن', 'د'],
    preview: 'معاينة',
    lastReviewed: 'آخر مراجعة',
    reportSubject: 'نتيجة فحص المخاطر الضريبية من TaxCheck',
    demoSubject: 'طلب عرض توضيحي',
    careerSubject: 'طلب توظيف',
    contactSubject: 'استفسار من الموقع',
    chooseRole: 'اختر الوظيفة',
    selectOne: 'اختر…',
    days: 'يوماً',
    calEmpty: 'لا مواعيد نهائية خلال 90 يوماً.',
    scrollHint: 'مرّر',
    minute: 'دقيقة',
    qa: 'سؤال وجواب',
    docsPerMin: 'مستند يُقرأ في الدقيقة',
  },
};
